name: Studio CI

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'studio/**'
      - '.github/workflows/studio-ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'studio/**'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential curl wget file libssl-dev \
            libayatana-appindicator3-dev librsvg2-dev

      - name: Install dependencies
        working-directory: studio
        run: pnpm install

      - name: Lint
        working-directory: studio
        run: |
          pnpm run lint
          pnpm run format:check

      - name: Type check
        working-directory: studio
        run: pnpm run type-check

      - name: Unit tests
        working-directory: studio
        run: pnpm run test -- --run

      - name: Build
        working-directory: studio
        run: pnpm tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: studio-${{ matrix.os }}
          path: |
            studio/src-tauri/target/release/bundle/**/*
          retention-days: 7

  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            build-essential curl wget file libssl-dev \
            libayatana-appindicator3-dev librsvg2-dev

      - working-directory: studio
        run: pnpm install

      - name: Install Playwright browsers
        working-directory: studio
        run: pnpm exec playwright install --with-deps chromium

      - name: Run E2E tests
        working-directory: studio
        run: pnpm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: studio/playwright-report/
          retention-days: 7

